import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useHostMultiPeerSession } from "@thebigsasha/react-peerjs-hooks";
import { JoinCode } from "../components/JoinCode";
import { VotableLi } from "./join";
import { Links } from "../components/Links";

interface Voter {
  name: string;
  vote?: string;
}

interface Host {
  name: string;
  question: string;
  options: string[];
  showResults?: boolean;
}

interface StateInterface {
  member: Voter | Host;
}

export default function Host() {
  const [peerStates, myState, setMyState, myID, numConnections, error] =
    useHostMultiPeerSession<StateInterface>({
      member: {
        name: "Host",
        question: "What is your favorite color?",
        options: ["Red", "Blue", "Green"],
      },
    });

  const { name, question, options, showResults } = myState.member as Host;

  const votes: { [key: string]: number } = {};

  for (const peerState of peerStates) {
    const { vote } = peerState.data.member as Voter;
    if (vote) {
      votes[vote] = (votes[vote] || 0) + 1;
    }
  }

  return (
    <>
      <Head>
        <title>Host a Poll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Host a Poll</h1>
          <JoinCode code={myID}></JoinCode>
        </div>

        <div className={styles.center}>
          <div>
            <br />

            <textarea
              id="question"
              rows={3}
              style={{ width: "100%" }}
              value={question}
              onChange={(e) => {
                setMyState({
                  member: { name, question: e.target.value, options },
                });
              }}
            />

            <br />

            <ul>
              {options.map((option) => {
                return (
                  <VotableLi key={option}>
                    <input
                      type="text"
                      value={option}
                      onChange={(e) => {
                        const newOptions = options.map((o) => {
                          if (o === option) {
                            return e.target.value;
                          }
                          return o;
                        });
                        setMyState({
                          member: { name, question, options: newOptions },
                        });
                      }}
                    />
                    {votes[option] || 0} votes
                    <button
                      onClick={() => {
                        setMyState({
                          member: {
                            name,
                            question,
                            options: options.filter((o) => o !== option),
                          },
                        });
                      }}
                    >
                      Remove
                    </button>
                  </VotableLi>
                );
              })}

              <VotableLi>
                <button
                  onClick={() => {
                    setMyState({
                      member: {
                        name,
                        question,
                        options: [
                          ...options,
                          `new options ${Math.random() * 100}`,
                        ],
                      },
                    });
                  }}
                >
                  Add Option
                </button>
                <div className={"std-borders"}>
                  {" "}
                  <label htmlFor="showResults">Show Results </label>
                  <input
                    type="checkbox"
                    id="showResults"
                    checked={showResults}
                    onChange={(e) => {
                      setMyState({
                        member: {
                          name,
                          question,
                          options,
                          showResults: e.target.checked,
                        },
                      });
                    }}
                  />
                </div>
              </VotableLi>
            </ul>
          </div>
        </div>

        <Links />
      </main>
    </>
  );
}
